import { OutcomeTracker } from "./outcome";

/**
 * Enterprise Conversation Analytics Engine.
 * Tracks resolution rates, CSAT, response latency, token costs, and top queries.
 */

export interface ConversationRecord {
  sessionId: string;
  startTime: number;
  endTime?: number;
  messageCount: number;
  resolved: boolean;
  handedOff: boolean;
  csatScore?: number;
  totalTokens: number;
  totalCostUsd: number;
  topQueries: string[];
  responseTimes: number[];
  model?: string;
  variantId?: string;
}

export interface AnalyticsSnapshot {
  totalConversations: number;
  resolvedCount: number;
  resolutionRate: number;
  handoffRate: number;
  avgCsatScore: number;
  avgResponseTimeMs: number;
  totalTokensUsed: number;
  totalCostUsd: number;
  totalValueGeneratedUsd: number; // Value generated by outcomes
  roi: number;                   // (Value - Cost) / Cost
  variants?: Record<string, {
    totalConversations: number;
    totalValueGeneratedUsd: number;
    resolutionRate: number;
    roi: number;
  }>;
  avgTokensPerConversation: number;
  avgCostPerConversation: number;
  topQueries: { query: string; count: number }[];
  conversationsPerHour: number;
}

export const OPENAI_PRICING: Record<string, { input: number; output: number }> = {
  "gpt-4o": { input: 5.0, output: 15.0 },
  "gpt-4o-mini": { input: 0.15, output: 0.6 },
  "gpt-3.5-turbo": { input: 0.5, output: 1.5 },
};

export class ConversationAnalytics {
  private records = new Map<string, ConversationRecord>();
  private queryFrequency = new Map<string, number>();
  public outcomeTracker?: OutcomeTracker;

  constructor(outcomeTracker?: OutcomeTracker) {
    this.outcomeTracker = outcomeTracker;
  }

  estimateTokens(text: string): number {
    return Math.ceil(text.length / 4);
  }

  calculateCost(model: string, tokens: number, type: "input" | "output" = "input"): number {
    const pricing = OPENAI_PRICING[model] || OPENAI_PRICING["gpt-4o-mini"];
    const rate = type === "input" ? pricing.input : pricing.output;
    return (tokens / 1_000_000) * rate;
  }

  startConversation(sessionId: string, model: string = "gpt-4o-mini", variantId?: string): void {
    if (!this.records.has(sessionId)) {
      this.records.set(sessionId, {
        sessionId,
        startTime: Date.now(),
        messageCount: 0,
        resolved: false,
        handedOff: false,
        totalTokens: 0,
        totalCostUsd: 0,
        topQueries: [],
        responseTimes: [],
        model,
        variantId,
      });
    }
  }

  recordQuery(sessionId: string, query: string): void {
    const record = this.records.get(sessionId);
    if (record) {
      record.messageCount++;
      record.topQueries.push(query);
      const tokens = this.estimateTokens(query);
      const cost = this.calculateCost(record.model || "gpt-4o-mini", tokens, "input");
      record.totalTokens += tokens;
      record.totalCostUsd += cost;
    }
    const normalized = query.toLowerCase().trim().slice(0, 100);
    this.queryFrequency.set(normalized, (this.queryFrequency.get(normalized) || 0) + 1);
  }

  recordResponse(sessionId: string, reply: string, latencyMs: number): void {
    const record = this.records.get(sessionId);
    if (record) {
      record.responseTimes.push(latencyMs);
      const tokens = this.estimateTokens(reply);
      const cost = this.calculateCost(record.model || "gpt-4o-mini", tokens, "output");
      record.totalTokens += tokens;
      record.totalCostUsd += cost;
    }
  }

  markResolved(sessionId: string): void {
    const record = this.records.get(sessionId);
    if (record) { record.resolved = true; record.endTime = Date.now(); }
  }

  markHandedOff(sessionId: string): void {
    const record = this.records.get(sessionId);
    if (record) { record.handedOff = true; record.endTime = Date.now(); }
  }

  recordCSAT(sessionId: string, score: number): void {
    const record = this.records.get(sessionId);
    if (record) record.csatScore = Math.max(1, Math.min(5, score));
  }

  getSnapshot(): AnalyticsSnapshot {
    const all = [...this.records.values()];
    const total = all.length;
    if (total === 0) return this.emptySnapshot();

    const resolved = all.filter(r => r.resolved).length;
    const handedOff = all.filter(r => r.handedOff).length;
    const withCsat = all.filter(r => r.csatScore !== undefined);
    const avgCsat = withCsat.length > 0
      ? withCsat.reduce((s, r) => s + (r.csatScore || 0), 0) / withCsat.length
      : 0;

    const allResponseTimes = all.flatMap(r => r.responseTimes);
    const avgResponseTime = allResponseTimes.length > 0
      ? allResponseTimes.reduce((a, b) => a + b, 0) / allResponseTimes.length
      : 0;

    const totalTokens = all.reduce((s, r) => s + r.totalTokens, 0);
    const totalCost = all.reduce((s, r) => s + r.totalCostUsd, 0);

    let totalValue = 0;
    if (this.outcomeTracker) {
      totalValue = this.outcomeTracker.getGlobalStats().totalValueUsd;
    }

    const now = Date.now();
    const firstConvo = all.length > 0 ? Math.min(...all.map(r => r.startTime)) : now;
    const hourSpan = Math.max(1, (now - firstConvo) / 3_600_000);

    const topQueries = [...this.queryFrequency.entries()]
      .sort((a, b) => b[1] - a[1])
      .slice(0, 20)
      .map(([query, count]) => ({ query, count }));

    const variants: Record<string, any> = {};
    const groupedByVariant = all.reduce((acc, r) => {
      const v = r.variantId || "default";
      if (!acc[v]) acc[v] = [];
      acc[v].push(r);
      return acc;
    }, {} as Record<string, typeof all>);

    for (const [variantId, vRecords] of Object.entries(groupedByVariant)) {
        const vTotal = vRecords.length;
        const vResolved = vRecords.filter((r) => r.resolved).length;
        
        let vValue = 0;
        if (this.outcomeTracker) {
            vRecords.forEach(r => {
                const outRecords = (this.outcomeTracker as any).outcomes?.get(r.sessionId) || [];
                vValue += outRecords.reduce((s: number, o: any) => s + o.valueUsd, 0);
            });
        }
        
        const vCost = vRecords.reduce((s, r) => s + r.totalCostUsd, 0);
        
        variants[variantId] = {
            totalConversations: vTotal,
            totalValueGeneratedUsd: vValue,
            resolutionRate: vTotal > 0 ? vResolved / vTotal : 0,
            roi: vCost > 0 ? (vValue - vCost) / vCost : 0
        };
    }

    return {
      totalConversations: total,
      resolvedCount: resolved,
      resolutionRate: resolved / total,
      handoffRate: handedOff / total,
      avgCsatScore: Math.round(avgCsat * 10) / 10,
      avgResponseTimeMs: Math.round(avgResponseTime),
      totalTokensUsed: totalTokens,
      totalCostUsd: Math.round(totalCost * 100000000) / 100000000,
      totalValueGeneratedUsd: Math.round(totalValue * 100) / 100,
      roi: totalCost > 0 ? (totalValue - totalCost) / totalCost : 0,
      avgTokensPerConversation: Math.round(totalTokens / total),
      avgCostPerConversation: Math.round((totalCost / total) * 100000000) / 100000000,
      topQueries,
      conversationsPerHour: Math.round((total / hourSpan) * 10) / 10,
    };
  }

  private emptySnapshot(): AnalyticsSnapshot {
    return {
      totalConversations: 0, resolvedCount: 0, resolutionRate: 0, handoffRate: 0,
      avgCsatScore: 0, avgResponseTimeMs: 0, totalTokensUsed: 0, totalCostUsd: 0,
      totalValueGeneratedUsd: 0, roi: 0,
      avgTokensPerConversation: 0, avgCostPerConversation: 0, topQueries: [],
      conversationsPerHour: 0,
    };
  }

  exportJSON(): string {
    return JSON.stringify({
      snapshot: this.getSnapshot(),
      records: [...this.records.entries()],
      freq: [...this.queryFrequency.entries()]
    }, null, 2);
  }

  importJSON(json: string): void {
    const data = JSON.parse(json);
    this.records = new Map(data.records);
    this.queryFrequency = new Map(data.freq);
  }

  reset(): void {
    this.records.clear();
    this.queryFrequency.clear();
  }
}
